import express, { Router, Request, Response } from "express";
import { Character } from "../../entity/Character";

const router: Router = express.Router();

//const characters = [
//  {
//    char_id: 1,
//    name: "Walter White",
//    birthday: "09-07-1958",
//    occupation: ["High School Chemistry Teacher", "Meth King Pin"],
//    img: "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_walter-white-lg.jpg",
//    status: "Presumed dead",
//    nickname: "Heisenberg",
//  },
//  {
//    char_id: 2,
//    name: "Jesse Pinkman",
//    birthday: "09-24-1984",
//    occupation: ["Meth Dealer"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/9/95/JesseS5.jpg/revision/latest?cb=20120620012441",
//    status: "Alive",
//    nickname: "Cap n' Cook",
//  },
//  {
//    char_id: 3,
//    name: "Skyler White",
//    birthday: "08-11-1970",
//    occupation: [
//      "House wife",
//      "Book Keeper",
//      "Car Wash Manager",
//      "Taxi Dispatcher",
//    ],
//    img: "https://s-i.huffpost.com/gen/1317262/images/o-ANNA-GUNN-facebook.jpg",
//    status: "Alive",
//    nickname: "Sky",
//  },
//  {
//    char_id: 4,
//    name: "Walter White Jr.",
//    birthday: "07-08-1993",
//    occupation: ["Teenager"],
//    img: "https://media1.popsugar-assets.com/files/thumbor/WeLUSvbAMS_GL4iELYAUzu7Bpv0/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2018/01/12/910/n/1922283/fb758e62b5daf3c9_TCDBRBA_EC011/i/RJ-Mitte-Walter-White-Jr.jpg",
//    status: "Alive",
//    nickname: "Flynn",
//  },
//  {
//    char_id: 5,
//    name: "Henry Schrader",
//    birthday: "Unknown",
//    occupation: ["DEA Agent"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/b/b7/HankS5.jpg/revision/latest/scale-to-width-down/700?cb=20120620014136",
//    status: "Deceased",
//    nickname: "Hank",
//  },
//  {
//    char_id: 6,
//    name: "Marie Schrader",
//    birthday: "Unknown",
//    occupation: ["Housewife", "Clepto"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/1/10/Season_2_-_Marie.jpg/revision/latest?cb=20120617211645",
//    status: "Alive",
//    nickname: "Marie",
//  },
//  {
//    char_id: 7,
//    name: "Mike Ehrmantraut",
//    birthday: "Unknown",
//    occupation: ["Hitman", "Private Investigator", "Ex-Cop"],
//    img: "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_mike-ehrmantraut-lg.jpg",
//    status: "Deceased",
//    nickname: "Mike",
//  },
//  {
//    char_id: 8,
//    name: "Saul Goodman",
//    birthday: "Unknown",
//    occupation: ["Lawyer"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/1/16/Saul_Goodman.jpg/revision/latest?cb=20120704065846",
//    status: "Alive",
//    nickname: "Jimmy McGill",
//  },
//  {
//    char_id: 9,
//    name: "Gustavo Fring",
//    birthday: "Unknown",
//    occupation: ["Los-Pollos co-Founder", "Philanthropist", "Cartel Leader"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/1/1f/BCS_S4_Gustavo_Fring.jpg/revision/latest?cb=20180824195925",
//    status: "Deceased",
//    nickname: "Gus",
//  },
//  {
//    char_id: 10,
//    name: "Hector Salamanca",
//    birthday: "Unknown",
//    occupation: ["Former Senior Cartel Leader"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/b/b4/Hector_BCS.jpg/revision/latest?cb=20170810091606",
//    status: "Deceased",
//    nickname: "Don Hector",
//  },
//  {
//    char_id: 11,
//    name: "Domingo Molina",
//    birthday: "Unknown",
//    occupation: ["Meth Distributor"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/e/e7/Krazy8.png/revision/latest?cb=20130208041554",
//    status: "Deceased",
//    nickname: "Krazy-8",
//  },
//  {
//    char_id: 12,
//    name: "Tuco Salamanca",
//    birthday: "Unknown",
//    occupation: ["Meth Distributor"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/a/a7/Tuco_BCS.jpg/revision/latest?cb=20170810082445",
//    status: "Deceased",
//    nickname: "Tuco",
//  },
//  {
//    char_id: 13,
//    name: "Marco & Leonel Salamanca",
//    birthday: "Unknown",
//    occupation: ["Cartel Hitman"],
//    img: "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_the-cousins-lg.jpg",
//    status: "Deceased",
//    nickname: "The Cousins",
//  },
//  {
//    char_id: 14,
//    name: "Lydia Rodarte-Quayle",
//    birthday: "Unknown",
//    occupation: ["Executive at Madrigal"],
//    img: "https://media1.popsugar-assets.com/files/thumbor/wERDST0TUb-iHCSb2r5ZpsvaZLo/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2013/07/17/675/n/1922283/fae2f583f04bb80f_Laura-Fraser-is-back-as-Lydia-Rodarte-Quayle_gallery_primary/i/Laura-Fraser-Lydia-Rodarte-Quayle.jpg",
//    status: "Deceased",
//    nickname: "Lydia",
//  },
//  {
//    char_id: 15,
//    name: "Todd Alquist",
//    birthday: "Unknown",
//    occupation: ["Lab Assistant", "Enforcer", "Meth Cook"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/9/95/Todd_brba5b.png/revision/latest?cb=20130717134303",
//    status: "Deceased",
//    nickname: "Ricky Hitler",
//  },
//  {
//    char_id: 16,
//    name: "Jane Margolis",
//    birthday: "Unknown",
//    occupation: ["Tattoo Artist", "Landlord"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/b/b4/Jane.jpg/revision/latest?cb=20090621233653",
//    status: "Deceased",
//    nickname: "Apology Girl",
//  },
//  {
//    char_id: 17,
//    name: "Skinny Pete",
//    birthday: "Unknown",
//    occupation: ["Low-level meth distributer"],
//    img: "https://vignette.wikia.nocookie.net/breaking-bad-tv/images/c/ce/Sp.png/revision/latest?cb=20121016143623",
//    status: "Alive",
//    nickname: "Skinny",
//  },
//  {
//    char_id: 18,
//    name: "Brandon Mayhew",
//    birthday: "Unknown",
//    occupation: ["Low-level meth distributer"],
//    img: "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_badger-lg.jpg",
//    status: "Alive",
//    nickname: "Badger",
//  },
//  {
//    char_id: 19,
//    name: "Huell Babineaux",
//    birthday: "Unknown",
//    occupation: ["Bodyguard"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/c/c1/4x11_-_Huell.png/revision/latest?cb=20130913100459&path-prefix=es",
//    status: "Alive",
//    nickname: "Huell",
//  },
//  {
//    char_id: 20,
//    name: "Steven Gomez",
//    birthday: "Unknown",
//    occupation: ["DEA Agent"],
//    img: "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_steven-gomez-lg.jpg",
//    status: "Deceased",
//    nickname: "Gomie",
//  },
//  {
//    char_id: 21,
//    name: "Theodore Beneke",
//    birthday: "Unknown",
//    occupation: ["Former President Beneke Fabricators"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/b/bd/Cast_bb_700x1000_todd-beneke-lg.jpg/revision/latest?cb=20170723165057",
//    status: "Alive",
//    nickname: "Ted",
//  },
//  {
//    char_id: 22,
//    name: "Gale Boetticher",
//    birthday: "Unknown",
//    occupation: ["Chemist", "Meth manufacturer"],
//    img: "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_gale-boetticher-lg.jpg",
//    status: "Deceased",
//    nickname: "GB",
//  },
//  {
//    char_id: 23,
//    name: "Andrea Cantillo",
//    birthday: "Unknown",
//    occupation: ["Unknown"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/5/51/Andrea_-_To%27hajilee.png/revision/latest?cb=20131025094457",
//    status: "Deceased",
//    nickname: "Andrea",
//  },
//  {
//    char_id: 24,
//    name: "Brock Cantillo",
//    birthday: "Unknown",
//    occupation: ["Kid"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/9/97/Brock.png/revision/latest?cb=20170725193144",
//    status: "Alive",
//    nickname: "Brock",
//  },
//  {
//    char_id: 25,
//    name: "Carmen Molina",
//    birthday: "Unknown",
//    occupation: ["High School Principal"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/d/de/Carmen.JPG/revision/latest?cb=20100410125233",
//    status: "Alive",
//    nickname: "Carmen",
//  },
//  {
//    char_id: 26,
//    name: "Gretchen Schwartz",
//    birthday: "Unknown",
//    occupation: ["Co-owner Gray Matter"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/5/5e/Gretchen_Schwartz.png/revision/latest?cb=20131005103735&path-prefix=es",
//    status: "Alive",
//    nickname: "Gretchen",
//  },
//  {
//    char_id: 27,
//    name: "Elliot Schwartz",
//    birthday: "Unknown",
//    occupation: ["Co-Founder Gray Matter"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/8/8a/Elliott_Schwartz.png/revision/latest?cb=20131005103743&path-prefix=es",
//    status: "Alive",
//    nickname: "Elliot",
//  },
//  {
//    char_id: 28,
//    name: "Gonzo",
//    birthday: "Unknown",
//    occupation: ["Tuco's Bodyguard"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/d/d6/Gonzo.JPG/revision/latest?cb=20100415212944",
//    status: "Deceased",
//    nickname: "Gonzo",
//  },
//  {
//    char_id: 29,
//    name: "Christian Ortgea",
//    birthday: "Unknown",
//    occupation: ["Low-level meth distributor"],
//    img: "https://res.cloudinary.com/dwvrok1le/image/upload/v1540314304/c8acek3pimb0hb4efrvf.jpg",
//    status: "Deceased",
//    nickname: "Combo",
//  },
//  {
//    char_id: 30,
//    name: "Mrs. Pinkman",
//    birthday: "Unknown",
//    occupation: ["unknown"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/a/a2/Tess_Harper.jpg/revision/latest?cb=20120923235754",
//    status: "Alive",
//    nickname: "Jesse's mom",
//  },
//  {
//    char_id: 31,
//    name: "Adam Pinkman",
//    birthday: "Unknown",
//    occupation: ["unknown"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/c/c9/AdamPinkman.png/revision/latest?cb=20141117180836&path-prefix=es",
//    status: "Alive",
//    nickname: "Jesse's dad",
//  },
//  {
//    char_id: 32,
//    name: "Jake Pinkman",
//    birthday: "Unknown",
//    occupation: ["Kid", "Jesse's little brother"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/a/a4/Jake.jpg/revision/latest?cb=20121214201656&path-prefix=de",
//    status: "Alive",
//    nickname: "Jake",
//  },
//  {
//    char_id: 33,
//    name: "No-Doze",
//    birthday: "Unknown",
//    occupation: ["Juarez Cartel Lieutenant"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/c/ca/No_Doze_2.png/revision/latest?cb=20131014073210",
//    status: "Deceased",
//    nickname: "No-Doze",
//  },
//  {
//    char_id: 34,
//    name: "Emilio Koyama",
//    birthday: "Unknown",
//    occupation: ["Low-level meth distributor"],
//    img: "https://vignette.wikia.nocookie.net/trbreakingbad/images/9/9c/Emilio.jpeg/revision/latest?cb=20161029192022",
//    status: "Deceased",
//    nickname: "Emilio",
//  },
//  {
//    char_id: 35,
//    name: "Dr. Delcavoli",
//    birthday: "Unknown",
//    occupation: ["Physician"],
//    img: "https://res.cloudinary.com/dwvrok1le/image/upload/v1540314509/lj5qlbe6xvmmpxnspz6y.jpg",
//    status: "Alive",
//    nickname: "Dr. Delcavoli",
//  },
//  {
//    char_id: 36,
//    name: "Wendy S.",
//    birthday: "Unknown",
//    occupation: ["Prostitute"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/c/cc/Wendy.jpg/revision/latest?cb=20170721162715",
//    status: "Alive",
//    nickname: "Wendy",
//  },
//  {
//    char_id: 37,
//    name: "Bogdan Wolynetz",
//    birthday: "Unknown",
//    occupation: ["Former owner of A1A Car Wash"],
//    img: "https://i.pinimg.com/originals/d5/c0/34/d5c0345ae70fbdbaa33b7537d685da54.jpg",
//    status: "Alive",
//    nickname: "Bogdan",
//  },
//  {
//    char_id: 38,
//    name: "Ken",
//    birthday: "Unknown",
//    occupation: ["Stock Broker"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/8/8c/Ken.png/revision/latest?cb=20170721163649",
//    status: "Alive",
//    nickname: "Ken Wins",
//  },
//  {
//    char_id: 39,
//    name: "Holly White",
//    birthday: "Unknown",
//    occupation: ["Infant"],
//    img: "https://static.wikia.nocookie.net/breakingbad/images/0/08/Tumblr_lqddc79K9S1qc5omm.png/revision/latest?cb=20111012055605",
//    status: "Alive",
//    nickname: "Holly",
//  },
//  {
//    char_id: 40,
//    name: "George Merkert",
//    birthday: "Unknown",
//    occupation: ["Former Head of Albuquerque DEA"],
//    img: "https://m.media-amazon.com/images/M/MV5BMTkwMTkxNjUzM15BMl5BanBnXkFtZTgwMTg5MTczMTE@._V1_UY317_CR175,0,214,317_AL_.jpg",
//    status: "Alive",
//    nickname: "ASAC Merkert",
//  },
//  {
//    char_id: 41,
//    name: "Donald Margolis",
//    birthday: "Unknown",
//    occupation: ["Air-Traffic Controller", "Landlord"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/1/12/Donald_Margolis.png/revision/latest?cb=20120802212034",
//    status: "Unknown",
//    nickname: "Jane's dad",
//  },
//  {
//    char_id: 42,
//    name: "Clovis",
//    birthday: "Unknown",
//    occupation: ["Mechanic"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/0/0f/Clovis.JPG/revision/latest?cb=20100415221013",
//    status: "Alive",
//    nickname: "Clovis",
//  },
//  {
//    char_id: 43,
//    name: "SAC Ramey",
//    birthday: "Unknown",
//    occupation: ["DEA agent"],
//    img: "https://res.cloudinary.com/dwvrok1le/image/upload/v1539360786/o7thsjdorobfbetqaefj.jpg",
//    status: "Alive",
//    nickname: "SAC Ramey",
//  },
//  {
//    char_id: 44,
//    name: "Victor",
//    birthday: "Unknown",
//    occupation: ["Henchman of Gustavo Fring"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/4/48/Victor2.png/revision/latest?cb=20131009225027",
//    status: "Deceased",
//    nickname: "Victor",
//  },
//  {
//    char_id: 45,
//    name: "Tomás Cantillo",
//    birthday: "Unknown",
//    occupation: ["Kid", "Gang member for a rival dealer in ABQ"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/e/ec/Tomas.png/revision/latest?cb=20130131043014",
//    status: "Deceased",
//    nickname: "Andrea's brother",
//  },
//  {
//    char_id: 46,
//    name: "Francesca Liddy",
//    birthday: "Unknown",
//    occupation: [
//      "Department of Motor Vehicles",
//      "Secretary for Saul Goodman Associates",
//    ],
//    img: "https://res.cloudinary.com/dwvrok1le/image/upload/v1539362182/o9mstjonfn6dsdi3uij6.jpg",
//    status: "Alive",
//    nickname: "Honey Tits",
//  },
//  {
//    char_id: 47,
//    name: "Cynthia",
//    birthday: "Unknown",
//    occupation: ["Los Pollos Hermanos Manager"],
//    img: "https://res.cloudinary.com/dwvrok1le/image/upload/v1539362375/z63youp272k5mbqbuqj9.jpg",
//    status: "Alive",
//    nickname: "Cynthia",
//  },
//  {
//    char_id: 48,
//    name: "Tortuga",
//    birthday: "Unknown",
//    occupation: ["Juarez Cartel member", "DEA informant"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/5/58/BBWA_Tortuga.jpg/revision/latest?cb=20131101172007",
//    status: "Deceased",
//    nickname: "Tortuga",
//  },
//  {
//    char_id: 49,
//    name: "Tim Roberts",
//    birthday: "Unknown",
//    occupation: ["Detective for the APD"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/8/8d/2x02_-_Tim_Roberts.jpg/revision/latest?cb=20110927053954",
//    status: "Alive",
//    nickname: "Detective Roberts",
//  },
//  {
//    char_id: 50,
//    name: "Juan Bolsa",
//    birthday: "Unknown",
//    occupation: ["Mexican drug cartel boss"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/3/38/Bolsa.png/revision/latest?cb=20180825204033",
//    status: "Deceased",
//    nickname: "Don Juan",
//  },
//  {
//    char_id: 51,
//    name: "Group Leader",
//    birthday: "Unknown",
//    occupation: ["Drug & Alcohol Rehabilitation Counselor"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/8/81/Group_Leader_Brown_Shirt_-_Kafkaesque.png/revision/latest?cb=20131025095333",
//    status: "Alive",
//    nickname: "Counselor",
//  },
//  {
//    char_id: 52,
//    name: "Kaylee Ehrmantraut",
//    birthday: "Unknown",
//    occupation: ["Kid"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/c/cc/Kaylee.png/revision/latest?cb=20170810082843",
//    status: "Alive",
//    nickname: "Mike's Granddaughter",
//  },
//  {
//    char_id: 53,
//    name: "Pamela",
//    birthday: "Unknown",
//    occupation: ["Attorney"],
//    img: "https://res.cloudinary.com/dwvrok1le/image/upload/v1539373707/bbb6muek0tcmbc3g2sog.jpg",
//    status: "Alive",
//    nickname: "Skyler's attorney",
//  },
//  {
//    char_id: 54,
//    name: "Duane Chow",
//    birthday: "Unknown",
//    occupation: ["Owner of Golden Moth Chemical"],
//    img: "https://res.cloudinary.com/dwvrok1le/image/upload/v1539373871/ssk1t4hvo9tmhvdt5hcn.jpg",
//    status: "Deceased",
//    nickname: "Chow",
//  },
//  {
//    char_id: 55,
//    name: "Stacey Ehrmantraut",
//    birthday: "Unknown",
//    occupation: ["Mother"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/b/b3/StaceyEhrmantraut.png/revision/latest?cb=20150310150049",
//    status: "Alive",
//    nickname: "Mike's daugter-in-law",
//  },
//  {
//    char_id: 56,
//    name: "Officer Saxton",
//    birthday: "Unknown",
//    occupation: ["APD Officer"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/f/f3/Officer_Saxton_-_I.F.T..png/revision/latest?cb=20131025090606",
//    status: "Alive",
//    nickname: "Saxton",
//  },
//  {
//    char_id: 57,
//    name: "Jack Welker",
//    birthday: "Unknown",
//    occupation: ["Criminal Gang Leader"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/c/ce/Jack5x13.png/revision/latest?cb=20130912225922",
//    status: "Deceased",
//    nickname: "Uncle Jack",
//  },
//  {
//    char_id: 112,
//    name: "Kimberly Wexler",
//    birthday: "Unknown",
//    occupation: ["Lawyer"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/f/f7/BCS_S4_Kim_Wexler.jpg/revision/latest?cb=20180824195845",
//    status: "Alive",
//    nickname: "Kim",
//  },
//  {
//    char_id: 113,
//    name: "Howard Hamlin",
//    birthday: "Unknown",
//    occupation: ["Lawyer"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/5/57/BCS_S4_Howard_Hamlin.jpg/revision/latest?cb=20180824195855",
//    status: "Alive",
//    nickname: "Howard",
//  },
//  {
//    char_id: 114,
//    name: "Charles McGill",
//    birthday: "Unknown",
//    occupation: ["Lawyer"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/3/3e/BCS_S3_ChuckMcGill.jpg/revision/latest?cb=20170327185308",
//    status: "Deceased",
//    nickname: "Chuck",
//  },
//  {
//    char_id: 115,
//    name: "Ignacio Varga",
//    birthday: "Unknown",
//    occupation: ["Crimal Gang Lieutenant"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/b/b1/BCS_S4_Nacho_Varga.jpg/revision/latest?cb=20180824195910",
//    status: "Alive",
//    nickname: "Nacho",
//  },
//  {
//    char_id: 116,
//    name: "Eduardo Salamanca",
//    birthday: "Unknown",
//    occupation: ["Cartel Member"],
//    img: "https://vignette.wikia.nocookie.net/breakingbad/images/8/85/LaloProfileBCS.png/revision/latest?cb=20180925050152",
//    status: "Alive",
//    nickname: "Lalo",
//  },
//];

//router.post("/characters", async (req: Request, res: Response) => {
//  characters.map((item) => {
//    const { name, birthday, occupation, img, status, nickname } = item;
//    const character = Character.create({
//      name,
//      birthday,
//      occupation,
//      img,
//      status,
//      nickname,
//    });
//    character.save();
//  });
//  return res.status(200).json("ok");
//});

//router.get("/characters", async (req: Request, res: Response) => {
//  try {
//    const characters = await Character.find();
//    return res.status(200).json(characters);
//  } catch (error) {
//    console.log(error);
//    return res.status(500).json(error);
//  }
//});

import UC from "../../usecases";
router.get("/characters", async (req: Request, res: Response) => {
  // const error = undefined
  // const value = true
  const { value, error } = await UC.EmployeesService.getCharacters();
  if (error) {
    res.status(500).json(error || new Error("UC undefined error"));
    return;
  }
  res.status(200).json(value);
});

export default router;
